Create pypi.md
hust-open-atom-club/hust-mirrors pull request #102
Opened 2024-10-31 16:39 UTC by SXP-Simon

Translation version for pypi.md in file docs.

2024-11-01 01:25 UTC, mudongliang commented on i18n/en/docusaurus-plugin-content-docs/current/pypi.md
> +PyPI (The Python Package Index),code-hosted at [https://pypi.org/](https://pypi.org/),is the official third-party software repository for the Python programming language.
逗号后面要添加空格

2024-11-01 01:26 UTC, mudongliang commented on i18n/en/docusaurus-plugin-content-docs/current/pypi.md
> +Encountering such kind of issue,you could try creating a virtual environment using venv, or use other virtual-environment-based package managers.
逗号后面要添加空格

2024-11-01 01:28 UTC, mudongliang commented on i18n/en/docusaurus-plugin-content-docs/current/pypi.md
> +PDM supports setting the package mirror using the `pdm config` command or environment variables. For long-term use, it is recommended to configure it through `pdm config`.
use "configuring the package mirror with the "

2024-11-01 01:29 UTC, mudongliang commented on i18n/en/docusaurus-plugin-content-docs/current/pypi.md
> +Set the package mirror using the `pdm config` command:
Config is more suitable than Set here

2024-11-01 01:52 UTC, mudongliang commented on i18n/en/docusaurus-plugin-content-docs/current/pypi.md
> +Poetry does not support configuring a global mirror, only project-specific configuration.
Poetry only supports project-specific configuration, instead of configuring a global mirror.

2024-11-01 01:53 UTC, mudongliang commented
@jingfelix For the content, please help double check.

2024-11-01 06:16 UTC, SXP-Simon commented
@jingfelix  now please check my fixed update.

2024-11-01 08:13 UTC, jingfelix requested changes

2024-11-01 08:13 UTC, jingfelix commented on i18n/en/docusaurus-plugin-content-docs/current/pypi.md
> +title: How to use Python Package Index
参考其他镜像源英文文档的标题，建议简化为 PyPI

2024-11-01 08:13 UTC, jingfelix commented on i18n/en/docusaurus-plugin-content-docs/current/pypi.md
> +PDM supports configuring the package mirror using the `pdm config` command or environment variables. For long-term leverage, it is recommended to configure it through `pdm config`.
> For long-term leverage

For long-term use

2024-11-01 08:34 UTC, SXP-Simon commented
@jingfelix 已修正

2024-11-03 12:17 UTC, mudongliang approved these changes

2024-11-03 16:02 UTC, jingfelix approved these changes

2024-11-03 16:04 UTC, merged

2024-11-03 16:12 UTC, jingfelix commented
@SXP-Simon Please contact @jingfelix in our WeChat Group to complete recruitment.