翻译了archlinuxcn为英文
hust-open-atom-club/hust-mirrors pull request #104
Opened 2024-11-01 16:44 UTC by CAICAIIs

翻译了archlinuxcn为英文

2024-11-02 13:26 UTC, tttturtle-russ requested changes
1. Keep the format consistent with origin file.
2. Also this pr introduces some compilation errors but I'm not sure why, need to figure it out.

2024-11-02 13:26 UTC, tttturtle-russ commented on i18n/en/docusaurus-plugin-content-docs/current/archlinuxcn.md
> +1. Edit the `/etc/pacman.conf file` add the following line to the top of the file:
`/etc/pacman.conf file` -> `/etc/pacman.conf`

2024-11-02 13:26 UTC, tttturtle-russ commented on i18n/en/docusaurus-plugin-content-docs/current/archlinuxcn.md
> +##One-click source switching
Missing whitespace

2024-11-02 13:26 UTC, tttturtle-russ commented on i18n/en/docusaurus-plugin-content-docs/current/archlinuxcn.md
> +Use the `echo`  command to add the address of the current mirror to the end of the software source configuration file:
Extra whitespace

2024-11-02 13:26 UTC, tttturtle-russ commented on i18n/en/docusaurus-plugin-content-docs/current/archlinuxcn.md
> +2.  [Help Repository](https://github.com/mirrorz-org/mirrorz-help)
Extra whitespace

2024-11-02 13:26 UTC, tttturtle-russ commented on i18n/en/docusaurus-plugin-content-docs/current/archlinuxcn.md
> +Use the `echo`  command to add the address of the current mirror to the end of the software source configuration file:
> the address of the current mirror

How about changing the `address` to `URL`? Also `software source configuration file` to `configuration file`

2024-11-02 13:26 UTC, tttturtle-russ commented on i18n/en/docusaurus-plugin-content-docs/current/archlinuxcn.md
> +The Arch Linux Chinese Community Repository, an unofficial software repository driven by the Arch Linux Chinese community, includes many additional packages not provided by the official repositories,
`community` -> `Community`

2024-11-02 14:30 UTC, CAICAIIs commented on i18n/en/docusaurus-plugin-content-docs/current/archlinuxcn.md
> +2.  [Help Repository](https://github.com/mirrorz-org/mirrorz-help)
Sorry, I didn't pay attention to this.

2024-11-02 14:52 UTC, CAICAIIs commented on i18n/en/docusaurus-plugin-content-docs/current/archlinuxcn.md
> +The Arch Linux Chinese Community Repository, an unofficial software repository driven by the Arch Linux Chinese community, includes many additional packages not provided by the official repositories,
I have already made the modifications

2024-11-02 16:16 UTC, tttturtle-russ commented
Content is good now. We just need to fix the compilation error.

2024-11-03 02:09 UTC, mudongliang commented
@CAICAIIs Please use the formatted git commit message. @tttturtle-russ When you merge this PR, please use **Square Merge**

2024-11-03 03:11 UTC, CAICAIIs commented
> @CAICAIIs Please use the formatted git commit message. @tttturtle-russ When you merge this PR, please use **Square Merge**
Thank you for the guidance. I am a beginner in this area and I am currently learning how to use it

2024-11-03 03:11 UTC, CAICAIIs commented
> @CAICAIIs Please use the formatted git commit message. @tttturtle-russ When you merge this PR, please use **Square Merge**

Thank you for the guidance. I am a beginner in this area and I am currently learning how to use it

2024-11-03 03:15 UTC, mudongliang commented
<img width="314" alt="截屏2024-11-03 11 13 55" src="https://github.com/user-attachments/assets/7219a07b-b827-40c1-82d9-fd6c94485261">

It's fine. For us, we can merge it as one commit. However, it's good for your future if you can write good git title and commit message.

2024-11-03 03:18 UTC, CAICAIIs commented
> <img alt="截屏2024-11-03 11 13 55" width="314" src="https://private-user-images.githubusercontent.com/6214861/382529686-7219a07b-b827-40c1-82d9-fd6c94485261.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MDQwODIsIm5iZiI6MTczMDYwMzc4MiwicGF0aCI6Ii82MjE0ODYxLzM4MjUyOTY4Ni03MjE5YTA3Yi1iODI3LTQwYzEtODJkOS1mZDZjOTQ0ODUyNjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDNUMDMxNjIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmY2Njc2MGFjODY5OGIyY2FmNjg4NTQxYjRhMGMzMDIzZTZlYjc1YmQwYjcwYjNkMmNmMjFlOGY1YTQyYmMwMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.vnBo3VhNDSMMpZ-RS7yP_gQKymVqHZMODUuLo9U4SsA">
> It's fine. For us, we can merge it as one commit. However, it's good for your future if you can write good git title and commit message.

You're right, I'm still unfamiliar with the operation. Thank you for pointing it out.

2024-11-03 05:20 UTC, CAICAIIs commented
> <img alt="截屏2024-11-03 11 13 55" width="314" src="https://private-user-images.githubusercontent.com/6214861/382529686-7219a07b-b827-40c1-82d9-fd6c94485261.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MTEwMjAsIm5iZiI6MTczMDYxMDcyMCwicGF0aCI6Ii82MjE0ODYxLzM4MjUyOTY4Ni03MjE5YTA3Yi1iODI3LTQwYzEtODJkOS1mZDZjOTQ0ODUyNjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDNUMDUxMjAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmQxNDA5NzIwMDg0N2ZlZDM4Mzc2ZDdiNmI3MGRmMzMwZDc3Mzk5NDM5ZDA1ZjUyMmQwZmQ3NzhiMDkzMDcxZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Y4OvKCCdLbLSNXHILCWsr8RThs3UtpVWJrPtHDULSIc">
> It's fine. For us, we can merge it as one commit. However, it's good for your future if you can write good git title and commit message.

Can you check again? Thank you for your careful guidance.

2024-11-03 05:22 UTC, mudongliang commented
You can check it yourself. The commits in this PR is kind of messy.

2024-11-03 05:28 UTC, mudongliang commented
For the commit history, you can check and refer to #102 #103

2024-11-03 05:32 UTC, CAICAIIs commented
> For the commit history, you can check and refer to #102 #103

Thank you, I am not yet able to handle my commit and am currently studying.

2024-11-03 05:35 UTC, mudongliang commented
> > For the commit history, you can check and refer to #102 #103
> 
> Thank you, I am not yet able to handle my commit and am currently studying.

No worry, keep learning. There is always a working method - keep your translation, create a new branch, copy the translation and create a new PR :)

2024-11-03 06:23 UTC, tttturtle-russ commented
> > > For the commit history, you can check and refer to #102 #103
> 
> > 
> 
> > Thank you, I am not yet able to handle my commit and am currently studying.
> 
> 
> 
> No worry, keep learning. There is always a working method - keep your translation, create a new branch, copy the translation and create a new PR :)

agree, the easiest way is to open a new pr. and you can check how the compilation bug occurred.

2024-11-03 12:18 UTC, mudongliang commented
duplicate with #105

2024-11-03 12:18 UTC, closed without merging