hlug description update
hust-open-atom-club/hust-mirrors pull request #135
Opened 2024-12-26 11:09 UTC by zeroifox

hlug description and hlug's logo update

2024-12-26 11:19 UTC, mudongliang commented on index.tsx
> +                <Translate id='mirror.footer.desc0_5'>华中科技大学Linux协会</Translate>
感觉有一点问题，社区或者俱乐部都是放在最下面，而不是跟学院或网络中心平级放在这里

2024-12-26 12:11 UTC, jingfelix requested changes

2024-12-26 12:11 UTC, jingfelix commented on index.tsx
这个文件应该在 `src/theme/Footer/index.tsx`

2024-12-26 12:11 UTC, jingfelix commented on hlug_logo.png
重复上传

2024-12-26 12:11 UTC, jingfelix commented on index.tsx
> +	<div className={styles.logos}>
这样的样式不太好看，且移动端下 hlug logo 会被拉伸，建议修改为
```html
        <div className={styles.logos}>
          <img className={styles.light} src='/img/atomclub.svg' height={80} />
          <img className={styles.dark} src='/img/atomclub-dark.svg' height={80} />
          <img className={styles.light} src='/img/hlug_logo.png' height={80} />
          <img className={styles.dark} src='/img/hlug_logo.png' height={80} />
        </div>
```

并且在 `src/theme/Footer/index.module.css` 中添加 `align-items`:
```css
.logos {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    min-width: 150px;
    align-items: center;
}
```

2024-12-26 14:21 UTC, jingfelix requested changes

2024-12-26 14:21 UTC, jingfelix commented on src/theme/Footer/index.tsx
> +              <Translate id='mirror.footer.desc0_2'>  和  </Translate>
这里是多添加了空格吗？

2024-12-26 14:21 UTC, jingfelix commented on src/theme/Footer/index.module.css
> +.logos {
添加到上面的`.logo`样式即可

2024-12-26 14:21 UTC, jingfelix commented on src/theme/Footer/index.tsx
> +              <Translate id='mirror.footer.desc6_0'>本站的源码可在</Translate> <a href='https://github.com/hust-open-atom-club/hust-mirrors'><Translate id='mirror.footer.desc6_1'>hust-mirrors 前端网站</Translat
这里没有添加英文翻译，但是修改了 i18n ID，会导致在英文下缺少 HLUG 部分的翻译
`https://github.com/hust-open-atom-club/hust-mirrors/blob/master/i18n/en/code.json`

2024-12-28 09:10 UTC, jingfelix approved these changes

2024-12-28 09:12 UTC, merged