Update releases.conf
hust-open-atom-club/hust-mirrors pull request #87
Opened 2024-10-10 14:52 UTC by ye527

[msys2]
名称=Msys2
路径=msys2/distrib/**
exp=^msys2/distrib/msys2-.+?.(exe|sfx.exe|tar.xz|tar.zx)$

[mxlinux]
name=Mxlinux
path=mxlinux/mx/repo/pool/main/l/linux/*
exp=^mxlinux/mx/repo/pool/main/l/linux/linux.+.(deb|dsc|tar.xz)$

2024-10-11 05:21 UTC, mudongliang commented
@jxlpzqc 请检查一下这个 PR

2024-10-11 07:16 UTC, jxlpzqc requested changes
请把 "名称" 改为 name, "路径" 改为 path

并且不要把文件修改写在 commit message 中

2024-10-11 07:19 UTC, jxlpzqc commented
@ye527 除此以外，mxlinux 应该匹配发行版安装包，文件在镜像站的 mxlinux-isos/ 中

2024-10-11 07:48 UTC, ye527 commented
修改：
[MSYs2]
name=Msys2
path=msys2/distrib/**
exp=^msys2/distrib/msys2-.+？.（exe|sfx.exe|tar.xz|tar.zx）$

[MXLINUX]
name=Mxlinux-isos
path=mxlinux-isos/mx/Final/**
exp=^mxlinux-isos/mx/Final/MX-.+\.（iso|iso\.md5|iso\.sha256|iso\.sig|iso\.zsync）$

2024-10-11 07:48 UTC, ye527 commented
修改：
[MSYs2]
name=Msys2
path=msys2/distrib/**
exp=^msys2/distrib/msys2-.+？.（exe|sfx.exe|tar.xz|tar.zx）$

[MXLINUX]
name=Mxlinux-isos
path=mxlinux-isos/mx/Final/**
exp=^mxlinux-isos/mx/Final/MX-.+.（iso|iso.md5|iso.sha256|iso.sig|iso.zsync）$

2024-10-11 10:11 UTC, ye527 commented
请问一下这次改对了吗

2024-10-11 10:13 UTC, ye527 commented
修改：
[MSYs2]
name=Msys2
path=msys2/distrib/**
exp=^msys2/distrib/msys2-.+?\.（exe|sfx.exe|tar.xz|tar.zx）$

[MXLINUX]
name=Mxlinux-isos
path=mxlinux-isos/mx/Final/**
exp=^mxlinux-isos/mx/Final/MX-.+\.（iso|iso.md5|iso.sha256|iso.sig|iso.zsync）$

2024-10-11 11:15 UTC, jingfelix commented
> exp=^mxlinux-isos/mx/Final/MX-.+.（iso|iso.md5|iso.sha256|iso.sig|iso.zsync）$

改为 `^mxlinux-isos\/MX\/Final\/.+\/MX-.+.iso$`  比较好

1. 中文标点
2. 大小写
3. 只匹配 ISO

2024-10-11 11:25 UTC, jxlpzqc commented
下面的 匹配模式串 测试有效：
```
[mxlinux]
name=MXLinux
path=mxlinux-isos/MX/Final/**
exp=^mxlinux-isos/MX/Final/([^/]+)/MX-(.+?)_.+\.iso$
version=2
variant=1
```

2024-10-11 12:14 UTC, ye527 commented
修改：
[mxlinux]
name=Mxlinux-isos
path=mxlinux-isos/mx/Final/**
exp=^mxlinux-isos/mx/Final/MX-.+.\iso$

2024-10-11 12:17 UTC, ye527 commented
修改：
[mxlinux]
name=Mxlinux-isos
path=mxlinux-isos/mx/Final/**
exp=^mxlinux-isos/mx/Final/MX-.+\.iso$

2024-10-11 12:18 UTC, ye527 commented
修改：
[mxlinux]
name=Mxlinux-isos
path=mxlinux-isos/mx/Final/**
exp=^mxlinux-isos/mx/Final/MX-.+.iso$
version=2
variant=1

2024-10-11 12:34 UTC, ye527 reviewed
[msys2]
name=Msys2
path=msys2/distrib/**
exp=^msys2/distrib/msys2-.+?\.(exe|sfx\.exe|tar\.xz|tar\.zx)$

[mxlinux]
name=Mxlinux-isos
path=mxlinux-isos/mx/Final/**
exp=^mxlinux-isos/mx/Final/MX-.+\.iso$
version=2
variant=1

2024-10-13 13:42 UTC, jingfelix commented
Duplicated with #89

2024-10-13 13:42 UTC, closed without merging