feat: add release conf test script
hust-open-atom-club/hust-mirrors pull request #88
Opened 2024-10-11 07:26 UTC by jxlpzqc

To test validity of release.conf, the script use rsync to fetch file list and test, and finally output a list generated.

2024-10-11 07:27 UTC, jxlpzqc commented
用于检测 contributor 提交的 releases.conf 是否能够匹配镜像站的文件

2024-10-13 13:00 UTC, jingfelix requested changes

2024-10-13 13:00 UTC, jingfelix commented on ci/test/test-releases-rsync.py
> +
可以加个 example，要不然之后的同学可能不会用

```bash
python3 ./test-releases-rsync.py --section msys2 --rsync rsync://mirrors.tuna.tsinghua.edu.cn/msys2 --prefix msys2/
```

2024-10-15 09:00 UTC, jingfelix approved these changes

2024-10-15 09:00 UTC, merged