Update releases.conf
hust-open-atom-club/hust-mirrors pull request #89
Opened 2024-10-11 12:32 UTC by ye527

[msys2]
name=Msys2
path=msys2/distrib/**
exp=^msys2/distrib/msys2-.+?\.(exe|sfx\.exe|tar\.xz|tar\.zx)$

[mxlinux]
name=Mxlinux-isos
path=mxlinux-isos/mx/Final/**
exp=^mxlinux-isos/mx/Final/MX-.+\.iso$
version=2
variant=1

2024-10-11 13:25 UTC, jxlpzqc requested changes

2024-10-11 13:25 UTC, jxlpzqc commented on ci/releases.conf
> +exp=^mxlinux-isos/mx/Final/MX-.+\.iso$
1. 应该使用大写 MX，且 Final 后还有一级目录
2. 该模式串不存在子模式，下面的 version 和 variant 无法匹配

2024-10-11 14:31 UTC, ye527 commented
已更改

2024-10-13 04:14 UTC, ye527 commented
请问这一次修改对了吗

2024-10-13 11:06 UTC, jingfelix requested changes

2024-10-13 11:06 UTC, jingfelix commented on ci/releases.conf
> +exp=^mxlinux-isos/MX/Final/(.+)/MX-.+\.iso$
MX- 后的内容需要匹配为子模式

exp=^mxlinux-isos/MX/Final/(.+)\/MX-(.+)\.iso$

2024-10-13 13:23 UTC, jingfelix commented
Check result:
cc @jxlpzqc 

<img width="953" alt="image" src="https://github.com/user-attachments/assets/525bfdda-c292-457d-aa62-63461cf03c07">

2024-10-13 13:24 UTC, jingfelix approved these changes

2024-10-15 08:50 UTC, jxlpzqc approved these changes

2024-10-15 08:57 UTC, merged